#!/usr/bin/env python

import os

from vimapt import Compress


class VimAptMakeVpb(object):
    def __init__(self):
        self.work_dir = os.getcwd()
        self.target_dir = os.path.dirname(self.work_dir)
        self.dir_name = os.path.basename(self.work_dir)

        # initial setup
        self.pkg_name, full_version = self.dir_name.split("_")
        self.version, self.revision = full_version.split("-")
        full_version = self.version + "-" + self.revision
        self.full_pkg_name = self.pkg_name + "_" + full_version + ".vpb"
        self.target_file = os.path.join(self.target_dir, self.full_pkg_name)

    def make(self):
        compress_object = Compress.Compress(self.work_dir, self.target_file)
        compress_object.compress()


if __name__ == "__main__":
    obj = VimAptMakeVpb()
    obj.make()
