#!/usr/bin/env python

import os
import subprocess


def main():
    work_dir = os.getcwd()
    for (dir_path, dir_names, file_names) in os.walk(work_dir):
        for dir_name in dir_names:
            pkg_dir = os.path.join(dir_path, dir_name)
            process_return = subprocess.call(["vimapt-makevpb"], shell=True, cwd=pkg_dir)
            if process_return == 0:
                print("%s build successful!" % dir_name)
            else:
                print("%s build failed!" % dir_name)
        break


if __name__ == "__main__":
    main()
