#!/usr/bin/env python

import os
import sys
from vimapt import Install


def main():
    home_dir = os.environ["HOME"]
    vim_dir = os.path.join(home_dir, ".vim")
    #print vim_dir
    package_relpath = sys.argv[1]
    package_abspath = os.path.realpath(package_relpath)
    install = Install.Install(vim_dir, package_abspath)
    install.install_package()


if __name__ == "__main__":
    main()
